### ISSUE TITLE
[Anon] Bug report: Chaos Space Marines - Codex.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-7th-edition#3248] opened 2017-01-17 01:37 UTC
**File:** Chaos Space Marines - Codex.catz

**BattleScribe version:** 2.10.65

**Platform:** Windows

**Dropbox:** Yes

**Description:** Cannot add more than 2 formation. when try to add CSM-CAD, CSM-CAD & CSM-FORMATION, nothing happen it hang

**Comment by francoisbeaulieu** [comment] 2017-01-17 17:08
Duplicate of #3244

**Closed as completed** 2017-01-17 20:18 UTC
Labels: duplicate
