### ISSUE TITLE
[Anon] Bug report: Chaos Space Marines - Codex.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-7th-edition#644] opened 2015-01-04 17:22 UTC
**File:** Chaos Space Marines - Codex.catz

**BattleScribe version:** 1.15.04

**Platform:** Windows

**Dropbox:** Yes

**Description:** In the options for almost every units' Aspiring Champion (so far tested on Bikes, Raptors, Chaos Space Marines, Noise Marines) the is no option to select 2 Lightning Claws, even though it would be legal to do so by surrendering both its Bolt Pistol and Close Combat weapon. Also Raptor Aspiring Champions are forced to select various ranged weapons that they can not legally even have, let alone be required to have (such as a Bolter).

**Comment by NebSeele** [comment] 2015-01-05 03:20
A profile carry over that I had not entirely ironed out, nice catch and thanks. I will see if I can get the melee weapons entry to work as intended (as most of the champions DO have 2 melee weapons).

The raptor champion may require its own unique weapon selection option to cater for the ability to swap in a ranged weapon from another of their weapons while not having the boltgun. They aren't allowed to have the boltgun (true) but the rest of those options are valid for them. If need be, I can rebuild the ranged weapon selection criteria for all of them. 

In any case, I am working on the bug at present, and should have it fixed in version 118.

**Closed as completed** 2015-01-05 08:02 UTC
Labels: profile/rule bug

**Comment by TheNightHaunter** [comment] 2015-01-09 23:31
I'm glad to be of service. Awesome fix btw!
