### ISSUE TITLE
[Anon] Bug report: Space Marines - Codex (2015).catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-7th-edition#1197] opened 2015-06-30 14:20 UTC
**File:** Space Marines - Codex (2015).catz

**BattleScribe version:** 1.15.06

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** I can not add anything to my force. Whenever i press à + to add to my force the program crasch and close down. This is hapening with SM codex 2015 only....

**Comment by amis92** [comment] 2015-06-30 15:27
Duplicate of #1152

**Closed as completed by amis92** 2015-06-30 15:27 UTC
Labels: duplicate
