### ISSUE TITLE
[Anon] Bug report: Space Wolves - Codex.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-7th-edition#3253] opened 2017-01-17 21:04 UTC
**File:** Space Wolves - Codex.catz

**BattleScribe version:** 2.00.22

**Platform:** Android

**Dropbox:** Yes

**Description:** After latest data update the following errors have occured
*THUNDERWOLVES*
-error saying minimum of 1 ranged weapon must be selected (this cannot be the case if x2 melee weapons are selected e.g chainsword & storm shield) 
-the previous error causes another error when x2 weapons are selected (i.e chainsword & storm shield) saying maximum of 2 weapons can be selected

*WOLF SCOUTS*
-error saying bolt guns must be selected, when another weapon has been selected to replace it i.e sniper rifle. 
-when bolt gun is selected another error states maximum of 1 weapon. 

The previous data patch was (to me) near perfect with next to no bugs? If we can either fix these mistakes or just go back to last space wolves data patch - that would be awesome!

**Comment by alphalas** [comment] 2017-01-17 21:07
duplicate of #3252 #3250, #3246,#3245

**Closed as completed by alphalas** 2017-01-17 21:07 UTC
Labels: duplicate

**Comment by FarseerVeraenthis** [comment] 2017-01-17 21:23
What Version of data file were you using??
Version 2023 does not have these issues
