### ISSUE TITLE
[Anon] Bug report: Astra Militarum - Codex.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-7th-edition#1648] opened 2015-12-05 14:48 UTC
**File:** Astra Militarum - Codex.catz

**BattleScribe version:** 1.15.07

**Platform:** Windows

**Dropbox:** Yes

**Description:** AStra Militarum Cadian battlegroup is empty, as are the formations. Formation detachment shows only the Sanctus Reach Formations, Steel Host and Rampart Detachment. None of the Cadian Battlegroup Formations are present.

**Comment by amis92** [comment] 2015-12-08 06:34
Duplicate of #1642.

**Closed as completed by amis92** 2015-12-08 06:34 UTC
Labels: duplicate
