### ISSUE TITLE
[Anon] Bug report: Space Marines - Codex (2015).catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-7th-edition#1201] opened 2015-06-30 20:11 UTC
**File:** Space Marines - Codex (2015).catz

**BattleScribe version:** 1.15.06

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** Start to make army list then locks the instant a selection is made and crashes the app

**Comment by amis92** [comment] 2015-07-01 07:05
Duplicate of #1152

**Closed as completed by amis92** 2015-07-01 07:05 UTC
Labels: duplicate
