### ISSUE TITLE
[Anon] Bug report: Chaos Space Marines - Codex.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-7th-edition#1669] opened 2015-12-14 06:25 UTC
**File:** Chaos Space Marines - Codex.catz

**BattleScribe version:** 1.15.07

**Platform:** Windows

**Dropbox:** No

**Description:** Cost for power weapons from the codex is only 15 points, on battlescribe its 15 points for the power weapons upgrade then another point cost for the type of weapon

**Comment by ecrousseau** [comment] 2015-12-17 02:46
I'm going to close this - can't reproduce - but please feel free to re-open if you can provide further details.

**Closed as completed by ecrousseau** 2015-12-17 02:46 UTC
Labels: point-cost bug
