### ISSUE TITLE
[Anon] Bug report: Astra Militarum - FW - Elysian.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-7th-edition#2830] opened 2016-11-20 21:11 UTC
**File:** Astra Militarum - FW - Elysian.catz

**BattleScribe version:** 2.00.09

**Platform:** Android

**Dropbox:** No

**Description:** The rooster states it requires a minimum of 1 Cypher. Its doing the same with, Heavy support (Vulture) Fast attack (Lightning and thunder bolts x2). 

Suggest fixing by changing the minimum value to 0.

**Comment by alphalas** [comment] 2016-11-21 01:54
duplicate of #2599

**Closed as completed by alphalas** 2016-11-21 01:54 UTC
Labels: duplicate
