### ISSUE TITLE
[Anon] Bug report: Space Marines - Codex (2015).catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-7th-edition#1121] opened 2015-06-24 08:51 UTC
**File:** Space Marines - Codex (2015).catz

**BattleScribe version:** 1.15.06

**Platform:** iPhone / iPod / iPad

**Dropbox:** Yes

**Description:** New space marine 2015 v2 is causing the application to crash as soon as you try to select any option I.e. Elites option

**Comment by amis92** [comment] 2015-06-24 10:28
Duplicate of #1119

**Closed as completed by amis92** 2015-06-24 10:28 UTC
Labels: duplicate
