### ISSUE TITLE
Bladewing Assault Brotherhood Formation issues

### ISSUE THREAD

**Issue by Xabre1342** [BSData/wh40k-7th-edition#2051] opened 2016-04-01 11:45 UTC
2 seperate issues found:

1) The Sergeant for the Assault squads do not have the option for jump packs.  The toggle in the squad itself is Jump Pack (3pts) // Sergeant (14pts) // Vet Sergeant (24pts) but no option after selecting the sergeants for their own jump packs, and no squad-wide jump pack like the CAD option allows.

2)  When selecting Raven Guard chapter tactics, Raven Guard relics do not come up.

**Comment by ddarz** [comment] 2016-04-01 14:25
Hello, I am afraid I am unable to reproduce these issues:

1) When selecting the blade wing, each squad has a checkbox for selecting jump packs, starts out at 15pts, 12pts for the 4 marines and 3pts for the sarge, so 4x3 + 3 = 15pts
This value increases for each additional marine, so it seems ok
Am I missing something?

2) Can you tell me where this issue appears? Each valid character and his armour options has the RG relics, both weapons and wargear. 

Could you post the steps you are using?

Cheers :)

**Comment by Xabre1342** [comment] 2016-04-01 15:11
This is using Formation Detachment, Space Marines v50, then selecting 
the BWB.  This is NOT from a Gladius.

**Comment by ddarz** [comment] 2016-04-01 15:17
Ah that must be the problem, its v51 currently
I tried it and it seems ok for the formation too

**Comment by Xabre1342** [comment] 2016-04-01 15:33
That did seem to fix it.  However, now the issue I run into is that 
Swiftstrike and Murder are two separate entries, and therefore always 
has two many weapons in the BP arm for the Chaplain.

**Comment by ddarz** [comment] 2016-04-01 15:40
yes that is a tough one to code, so it has been done arm by arm.
Choose one weapon for one arm, and then scroll down for the other arm, there will be a another selection box with the claws. Careful not to pay the 35pts twice
It's not ideal, but it works for now

**Comment by Xabre1342** [comment] 2016-04-01 15:53
Don't see an option for both.

Plus the Raven's Fury is a jump pack, so doesn't need to replace a weapon.

**Comment by ddarz** [comment] 2016-04-01 16:04
1) Take a captain, chaplain or Librarian
2) Under their armour, you will see their choices split into bolt pistol arm, chainsword arm and wargear.
3) For the bolt pistol arm, Under "Chapter Relics -Raven Guard Hand weapons", choose Murder
3.5) Scroll down
4) For the chainsword arm, Under "Chapter Relics -Raven Guard Hand weapons", choose Swiftstrike
4.5) Scroll down again
5) Under "Chapter Specific Wargear Relics", choose Ravens Fury

6) Note in wonder how you can also take Ex tenebris in addition, as it does not replace a weapon
7) Slap on the Raven Skull relic too, why not

I just tried all the above, worked fine :)
You are using the SM catalogue right? not the deprecated RG only one (we deleted that months ago)

**Comment by Xabre1342** [comment] 2016-04-01 16:40
in the BWB formation, the Captain has both options, divided by arms, so 
that one is correct.  The Chaplain does not; it has it ABOVE the two 
weapon arms (see the picture I sent last time), and only listed once.

**Comment by ddarz** [comment] 2016-04-01 16:45
Apologies, I can't see any picture :(
Aha! so the problem is with the chaplain, sorry I didnt read that properly
Ok I will take another look

**Comment by Xabre1342** [comment] 2016-04-01 17:02
No worries.  yeah, Chaplain in the BWB formation doesn't show all the 
variations.  Might be that the formation draws on an older chaplain 
code?  Dunno.

Thanks for chatting.

**Comment by ddarz** [comment] 2016-04-08 14:52
made a fix for this just now, 'should' be ok

**Closed as completed by ddarz** 2016-04-08 14:52 UTC
Labels: bug
