### ISSUE TITLE
[Anon] Bug report: Chaos - Khorne Daemonkin.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-7th-edition#896] opened 2015-04-09 19:15 UTC
**File:** Chaos - Khorne Daemonkin.catz

**BattleScribe version:** 1.15.07

**Platform:** Windows

**Dropbox:** No

**Description:** Description: Khorne Daemonkin: Some options for the Herald are missing ("Gaben des Khorne" (german), the table with e.g. the juggernaut).

**Comment by amis92** [comment] 2015-04-09 20:29
Duplicate of #895.

**Closed as completed by amis92** 2015-04-09 20:29 UTC
Labels: duplicate
