### ISSUE TITLE
[Anon] Bug report: Chaos Daemons (40K) - Codex.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-7th-edition#3019] opened 2016-12-09 22:28 UTC
**File:** Chaos Daemons (40K) - Codex.catz

**BattleScribe version:** 2.00.07

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** When I go to use the pandemoniad of tzeentch detachment it does not load.

**Comment by cartag** [comment] 2016-12-10 00:36
Duplicate of #3012

**Closed as completed by cartag** 2016-12-10 00:36 UTC
Labels: duplicate
