### ISSUE TITLE
Craftworld/wraithknight issues

### ISSUE THREAD

**Issue by Malkurnous** [BSData/wh40k-7th-edition#3853] opened 2017-06-12 18:38 UTC
**File/Catalogue:** craftworlds.cat

**BattleScribe version:** 2.01.00

**Platform:** Android

**Dropbox:** No

2 things. 

Autarch with swooping wings is currently only able to select 1 autarch weapon instead of 2.

Unable to add a lord of war (wraithknight) to any detachment, causes BattleScribe to stop.

**Comment by USSX-Hares** [comment] 2017-06-12 19:56
Wraithknight works fine from PC / Win7 / 2.01.00.87.
![default](https://user-images.githubusercontent.com/29100587/27052356-277227ee-4fc2-11e7-86d3-e2ef7b042920.png)

Don't even mind what could go wrong. Can you add Lord of War units from other factions?
![default](https://user-images.githubusercontent.com/29100587/27052350-20ce544e-4fc2-11e7-9e7a-39337b6a7b0c.png)

**Comment by FarseerVeraenthis** [comment] 2017-06-12 19:56
Autarch weapon selection was broken for all types, is now fixed :smile:

I can't reproduce the Wraithknight issue, even with a super-heavy detachment including three of them...

**Comment by Malkurnous** [comment] 2017-06-12 20:46
I tried every other faction, they all work, 

All detachments involving an eldar LoW choice just crashes battlescribe,

**Comment by FarseerVeraenthis** [comment] 2017-06-12 21:05
which is not great for you, but it works fine on my PC, and as USSX shows above, it works fine on his PC too. I can't test it on Android though... I'll see if one of the other Dev's can load up a Wraithknight on Android...

**Comment by FarseerVeraenthis** [comment] 2017-06-12 21:27
Which file version are you using?
I'm now on Version 9 which appears to work fine on Android. (Tested by @tag8833 )

**Comment by Malkurnous** [comment] 2017-06-12 21:57
I think I know what it is, but could be coincidence; i'm using battlescribe version 2.01.00, but I downloaded battlescribe on my partners android but it was version 2.01.01.... Gonna try to reinstall it and see if it makes a difference 

Thanks to everyone who helped though, such a great community

**Comment by FarseerVeraenthis** [comment] 2017-06-12 22:00
no problems :smile:

**Closed as completed** 2017-06-12 22:00 UTC
Labels: deprecated
