### ISSUE TITLE
[Anon] Bug report: Chaos Space Marines - Codex.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-7th-edition#1409] opened 2015-09-05 14:55 UTC
**File:** Chaos Space Marines - Codex.catz

**BattleScribe version:** 1.15.07

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** The [gosh darn] entries for anything pertaining to Slaanesh have been removed, you [not-nice doodieheads].

Stop removing shit that's part of the [maternal relations] codex

**Comment by cartag** [comment] 2015-09-05 14:57
Wow, that escalated quickly. Can you list what is missing? There shouldn't be anything that is part of the codex that is not in the file. If you can be specific, it will give me something to work with.

**Comment by amis92** [comment] 2015-09-05 17:38
Well, I'd say the answer for your question will be close to "fuck you, motherfucker". https://www.youtube.com/watch?v=GDQCaGlqLFY

**Comment by NebSeele** [comment] 2015-09-06 07:01
Ok then.. not the best way to report an issue.

Still... I can confirm that the Noise Marines and the [FW] Emperors Children Sonic Dreadnought are both missing from the roster (as of ver 163), as well as Be'lakor. All three are still in the catalogue and require linking to the correct spots. In addition, the Slaanesh mark and Lucius the Eternal are both still clearly in the roster as well. 

At present I am not sure what cartag is up to with his own reworking of the catalogue, and I won't have proper internet for at least 72 hrs (or time, just moved), so I am unable to provide a bugfix at this time.

**Comment by cartag** [comment] 2015-09-06 07:13
I'm working on it right now actually. I moved all the profiles for individual units into shared entries, there were a few thta didn't get linked proper after that. I missed a few things here and there, and I'm going through in depth for 164. It's already fixed, I'm just going through with a fine tooth comb.

**Comment by NebSeele** [comment] 2015-09-06 07:22
It's all good, you did an excellent job on something that would have been absolutely painful to do. It will make the catalogue easier to maintain until the new codex drops... whenever that turns out to happen.

**Comment by cartag** [comment] 2015-09-06 07:49
Resolved with #1414. This gives me something to do while I'm out of work, and I get a great deal of satisfaction from it. I'm tempted to go further and have it hide or show mounts and artifacts if you have a certain mark equipped, same with the icons. Only show the ones for the appropriate mark you have selected.

**Comment by NebSeele** [comment] 2015-09-06 08:27
Didn't think of that... though honestly I would probably have that happen in the next codex catalogue (assuming GW keeps chaos mounts, who knows these days)

**Comment by cartag** [comment] 2015-09-06 16:04
My goal with the dex is to make ours the one that other factions want to copy for their layout.

**Closed as completed** 2015-09-07 23:09 UTC
Labels: bug, profile/rule bug
