### ISSUE TITLE
[Anon] Bug report: Necrons - Codex (2015).catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-7th-edition#1484] opened 2015-10-03 00:33 UTC
**File:** Necrons - Codex (2015).catz

**BattleScribe version:** 1.15.07

**Platform:** Android

**Dropbox:** Yes

**Description:** I got the pro version to try to resolve the missing formations but to my disappointment they were not there either. Please update  and include  the 3 missing formations for star god, flayed ones and deathmarks

**Comment by amis92** [comment] 2015-10-04 18:40
These are not formations. Duplicate of #1480.

**Closed as completed by amis92** 2015-10-04 18:40 UTC
Labels: duplicate, invalid
