### ISSUE TITLE
[Anon] Bug report: Chaos Space Marines - Codex.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-7th-edition#1451] opened 2015-09-18 11:41 UTC
**File:** Chaos Space Marines - Codex.catz

**BattleScribe version:** 1.15.07

**Platform:** Windows

**Dropbox:** No

**Description:** When selecting Typhus (tried both with and without warlord) does not enable plague zombie option for cultist nor does it create new unit to select

**Comment by Itsacon** [comment] 2015-09-18 13:29
Duplicate of #1433

This works fine for me. Are you sure you have the latest version of the datafiles?

**Comment by rgMarkon** [comment] 2015-09-18 14:05
I've reinstalled battlescribe, i've deleted and redownloaded all the datafiles... i have tried to only replace the CSM files but still the same issue.. I had no problems a while ago but today when i opened my list it gave me an error and basically deleted the list  and afterwards i haven't been able to find the zombies... also on a different note... the hellbrute is listed at 100points and not 105 so i am not sure if its my battlescribe thats messing up right now

**Comment by NebSeele** [comment] 2015-09-18 15:52
The helbrute was errata'd to be 100pts immediately after the codex release, was that cost in the non english copies I believe and is pretty much still that cost via a 7th Ed errata and the Khorne Daemonkin file. As for the plague zombies, I am sure it was fixed but I can look at it tomorrow if this hasn't been resolved by then.

**Closed as completed** 2015-09-18 16:01 UTC
Labels: duplicate
