### ISSUE TITLE
[Anon] Bug report: Space Wolves - Codex.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-7th-edition#3252] opened 2017-01-17 20:20 UTC
**File:** Space Wolves - Codex.catz

**BattleScribe version:** 2.00.23

**Platform:** Android

**Dropbox:** No

**Description:** Wolf scouts will not allow you to set the bolt gun hand to 0.

Thunderwolf calvary requires you to have a ranged weapon, there is no such requirement in the codex.

Thanks!

**Comment by alphalas** [comment] 2017-01-17 20:34
duplicate of #3246 #3245

**Closed as completed by alphalas** 2017-01-17 20:34 UTC
Labels: duplicate

**Comment by FarseerVeraenthis** [comment] 2017-01-17 21:24
This is fixed as of File Version 2023.
Please update your data
