### ISSUE TITLE
[Anon] Bug report: Space Marines - Codex (2015).catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-7th-edition#2808] opened 2016-11-18 02:52 UTC
**File:** Space Marines - Codex (2015).catz

**BattleScribe version:** 2.00.05

**Platform:** Windows

**Dropbox:** No

**Description:** Roster is flagged invalid when I try to do a 5-man sternguard-squad with 2 heavy/special weapons. I add 2 veterans (heavy/special weapon), bringing the squad to 7 models, and then remove 2 normal veterans to bring the squad back down to 5, however BattleScribe now tells me that there must be a minimum of 4 veterans, so I guess the error is that the heavy/special weapon veterans do not count.

**Comment by francoisbeaulieu** [comment] 2016-11-21 03:17
Duplicate of #2780

**Closed as completed** 2016-11-21 03:20 UTC
Labels: duplicate
