### ISSUE TITLE
[Anon] Bug report: Space Wolves - Codex.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-7th-edition#1887] opened 2016-02-17 22:23 UTC
**File:** Space Wolves - Codex.catz

**BattleScribe version:** 1.15.09

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** Missing Detachments from The Curse Of The Wulfen and missing Dedicated Transport for Wulfen Units

**Comment by JusticarGames** [comment] 2016-02-18 00:13
Are we suppose to be throwing stuff up on here that is missing from the Curse of the Wulfen? Because it's nearly everything. I figure you guys will work on it when you get your hands on a actual copy, or do you rely strictly on our input?

**Comment by hisop** [comment] 2016-02-18 08:51
It will be sorted ASAP, i will go over all the options as soon as i have the rules.

**Comment by MasterSlowPoke** [comment] 2016-02-19 00:23
duplicate of #1881

**Closed as completed by MasterSlowPoke** 2016-02-19 00:23 UTC
Labels: duplicate
