### ISSUE TITLE
Sentinels of Terra centurions

### ISSUE THREAD

**Issue by Lynkon** [BSData/wh40k-7th-edition#1247] opened 2015-07-09 22:34 UTC
Sentinels of Terra no longer lists Centurion Devastator squads under elite or Centurion Assault squads under fast attack.

**Comment by afraeve** [comment] 2015-07-10 11:45
Duplicate of #1237

I've fixed this a couple days ago & pushed to Github - the update will be available in the next release.

**Closed as completed by afraeve** 2015-07-10 11:45 UTC
Labels: duplicate
