### ISSUE TITLE
[Anon] Bug report: Chaos Space Marines - Codex.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-7th-edition#837] opened 2015-03-29 12:42 UTC
**File:** Chaos Space Marines - Codex.catz

**BattleScribe version:** 1.14.07

**Platform:** Android

**Dropbox:** No

**Description:** For the FW legacys of ruin, currently only 0-1 is available per vehicle. However IA 13 says that each vehicle can take 'one or more' so multiple legacys per vehicle are permissible

**Comment by NebSeele** [comment] 2015-03-29 12:52
Don't know about the one or more, but the omission of the one only does make an interesting case (1 vehicle per 1000 pts and only 1 of each legacy per army (and no daemonic possession/Daemon Engine shenanigans) are the restrictions. I just checked it).

Honestly, while it does technically count as a bug under RAW... I am not sure about this one. Rules as written and Rules as Intended are two different things (that and practicality in an army, why load ALL the eggs in a basket that'll bring Str 8-D right to it).

Edit: That's not to say I won't fix it, though a side issue with the cost requirements has made me think on how to do the entry correctly. Also, slight wording issues corrected

**Closed as completed** 2015-04-06 11:05 UTC
Labels: bug, enhancement, vague report
