### ISSUE TITLE
[Anon] Bug report: Space Wolves - Codex.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-7th-edition#2642] opened 2016-11-03 23:31 UTC
**File:** Space Wolves - Codex.catz

**BattleScribe version:** 2.00.06

**Platform:** Android

**Dropbox:** No

**Description:** Invalid alert for space wolves army. i tested on android and windows. Other army worked corectly. Your apk is the best. Good job and good luck in the future.

**Comment by Gnofry** [comment] 2016-11-05 03:50
Same issue as #2631

**Comment by alphalas** [comment] 2016-11-08 13:44
Duplicate of #2631

**Closed as completed by alphalas** 2016-11-08 13:44 UTC
Labels: duplicate
