### ISSUE TITLE
[Anon] Bug report: Warhammer40K.gstz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-7th-edition#3367] opened 2017-02-05 19:43 UTC
**File:** Warhammer40K.gstz

**BattleScribe version:** 2.00.11

**Platform:** Windows

**Dropbox:** No

**Description:** Space Marine CADs cannot have any additional formations added.  Program just hangs if I try to add a formation detachment.

**Comment by FarseerVeraenthis** [comment] 2017-02-05 20:30
duplicate of #3332 
We're working on it...

**Closed as completed by FarseerVeraenthis** 2017-02-05 20:30 UTC
Labels: duplicate
