### ISSUE TITLE
[Anon] Bug report: Chaos Space Marines - Codex.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-7th-edition#2486] opened 2016-09-21 13:22 UTC
**File:** Chaos Space Marines - Codex.catz

**BattleScribe version:** 1.15.08

**Platform:** Android

**Dropbox:** No

**Description:** Units within the Chaos Black Crusade Detachment are meant to have the option to take Veterans of the Long War special rule for free due to the Death to the False Emperor rule. However, currently units within the detachment are required to spend points to pick up VotLW.

**Comment by cartag** [comment] 2016-09-21 13:25
Duplicate of #2460. This won't be happening until BS 2.0, There simply isn't a way to implement it with the options available in BS1.X

**Closed as completed by cartag** 2016-09-21 13:25 UTC
Labels: duplicate

**Comment by balannear** [comment] 2016-09-23 16:04
how to install bs2.0?
