### ISSUE TITLE
Bug Report: Chaos Space Marines - Codex.cat

### ISSUE THREAD

**Issue by Dragoneryx** [BSData/wh40k-7th-edition#2093] opened 2016-04-13 09:45 UTC
Platform(s): Windows, Android
Version: Chaos Space Marines v194

Obliterators: (p42 & p102)
Wargear: Fleshmetal, **Power fist**

However, there is no listing or mentioning of a power fist in the BattleScribe profile.

**Comment by OftKilted** [comment] 2016-04-13 13:34
Duplicate of #2082

**Closed as completed by OftKilted** 2016-04-13 13:34 UTC
Labels: duplicate
