### ISSUE TITLE
[Anon] Bug report: Chaos Space Marines

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-7th-edition#1352] opened 2015-08-10 08:54 UTC
**File:** Warhammer40K.gstz

**BattleScribe version:** 1.14.07

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** Keeps giving me chosen or possessed as a troop choice in standard com
Does it on lap top also
Gives me options for supplement artefacts but not the black mace

**Comment by NebSeele** [comment] 2015-08-10 09:21
If you are still around or able to read this anon: Is it possible for you to tell me which model can not take the black mace? By default the vanilla options should be the readily available options, not the supplement options.

As for the chosen/possessed showing up: That's possibly a mobile battlescribe issue, as I can duplicate the issue on my own iPhone but not the desktop machine. In addition it shows FW models as well on the iphone, as well as terminator weapon options in the chaos lord entry despite it being power armour. No idea how to fix the mobile bug when the desktop is working as intended.

**Comment by NebSeele** [comment] 2015-08-20 08:00
I am going to close this. I am not sure how to fix this one without re-writing the catalogue and even then that may not work

**Closed as completed by NebSeele** 2015-08-20 08:00 UTC
Labels: BattleScribe bug
