### ISSUE TITLE
Space Marines - Gladius Strike Force Chaplain Issue

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-7th-edition#2997] opened 2016-12-08 04:50 UTC
**File:** Space Marines - Codex (2015).catz

**BattleScribe version:** 2.00.09

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** The gladius strike force for the Chaplin Demi company wants you to add two chaplains. If you have one and delete the other it gives you the error that you need to add a Chaplin even though you still have one.

**Comment by FarseerVeraenthis** [comment] 2016-12-08 08:33
This is a duplicate of #2860

**Closed as completed by FarseerVeraenthis** 2016-12-08 08:33 UTC
Labels: duplicate
