### ISSUE TITLE
[Anon] Bug report: Astra Militarum - Codex.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-7th-edition#1635] opened 2015-12-01 07:22 UTC
**File:** Astra Militarum - Codex.catz

**BattleScribe version:** 1.15.07

**Platform:** Windows

**Dropbox:** No

**Description:** Details:
There were some problems with your data files. If you continue, this may lead to crashes or other strange behaviour.

> Astra Militarum: Codex (2014) v36: The catalogue data file is invalid:
> net.battlescribe.model.catalogue.Modifier@1d2354c: Modifier must have a child that exists
>     at net.battlescribe.desktop.rostereditor.g.f(BattleScribe:232)
>     at net.battlescribe.desktop.rostereditor.g.b(BattleScribe:510)
>     at net.battlescribe.desktop.rostereditor.g.b(BattleScribe:45)
>     at net.battlescribe.desktop.rostereditor.g$2.actionPerformed(BattleScribe:350)
>     at javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
> **EDIT: stacktrace snipped**

**Comment by amis92** [comment] 2015-12-01 13:15
Duplicate of #1626. Thanks for report.

**Closed as completed by amis92** 2015-12-01 13:15 UTC
Labels: bug
