### ISSUE TITLE
[Anon] Bug report: Warhammer40K.gstz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-7th-edition#2519] opened 2016-10-06 15:11 UTC
**File:** Warhammer40K.gstz

**BattleScribe version:** 1.15.07

**Platform:** Windows

**Dropbox:** No

**Description:** Genestealer Cult Codex has Purestrain Genestealers at 2 Attacks like Tyranids.  This is not correct as they are 3 attacks base in Genestealer Cult.

Thank you!

**Comment by GenWilhelm** [comment] 2016-10-06 17:31
Duplicate of #2517

**Closed as completed by GenWilhelm** 2016-10-06 17:31 UTC
Labels: duplicate
