### ISSUE TITLE
[Anon] Bug report: Chaos Space Marines - Codex.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-7th-edition#1335] opened 2015-08-02 23:55 UTC
**File:** Chaos Space Marines - Codex.catz

**BattleScribe version:** 1.15.07

**Platform:** Windows

**Dropbox:** No

**Description:** Chaos Chosen Champion can have a plasma gun, meltagun, flamer, etc.  The codex says "up to four models may choose...", thus the Heavy weapons maxSelections limit for Chosen should be decremented by 1.  Furthermore, "one chosen may replace his boltgun with one of the following".

Thus, it is possible for a 5 man Chosen group to have 5 plasma guns, meltaguns, etc.

**Comment by pruneface** [comment] 2015-08-03 23:14
Chosen champion can not have a flamer, plasma/melta gun he can only take a combi-melta/flamer/plasma the same as any other unit in this codex such as plague marines or chaos terminators and the 'any model' should be taken as 'any chosen' the same as the other codex entries plus you çan still have 5 plaßma guns but you need to take an additional guy

**Comment by amis92** [comment] 2015-08-19 12:49
@pruneface so... I'm not sure, do you say this report is completely invalid, or just a part of it?

**Comment by pruneface** [comment] 2015-08-20 00:15
I would say completely invalid bud due to the weapon selections for the chosen being different to the selections for the champion and the 'any model' in the codex should be 'any chosen' instead which is how all of the other units in the codex work (i will try emailing gw tomorrow to check if that is correct though bit it would seem odd for them to be different to all the others in the codex)

**Comment by NebSeele** [comment] 2015-08-20 04:45
It's largely the consensus here and elsewhere that the champion does NOT have access to the same weapons, and in this case that would include the special weapons and heavy weapon. Until a verdict from GW that isn't "consult your opponent" comes in, that's probably how it should be treated.

This of course, actually makes this error invalid under Rules as Intended. Rules as written... well there's enough issues with it in Codex: CSM and other codices. 

I'll close this issue for now as it's not something that really needs to be fixed in a catalogue that still needs some fixes to tie it in with 7th Ed layouts, at least until the next CSM codex anyways.

**Closed as completed by NebSeele** 2015-08-20 04:45 UTC
Labels: invalid, vague report
