### ISSUE TITLE
[Anon] Bug report: Adepta Sororitas.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-7th-edition#1777] opened 2016-01-16 03:48 UTC
**File:** Adepta Sororitas.catz

**BattleScribe version:** 1.15.07

**Platform:** Android

**Dropbox:** Yes

**Description:** I did find out how to add hospitars and standard bearers. But the standard bearers should be able to swap weapons eg. Bolter for flamer.

**Comment by penguin20000** [comment] 2016-01-16 10:18
Duplicate of #1776 i'll add this extra info to that bug.

**Closed as completed** 2016-01-16 10:19 UTC
Labels: duplicate, invalid

**Comment by hisop** [comment] 2016-01-17 12:45
This is incorrect. it specifically states:
-One Celestian may be upgraded to a Hospitaller, replacing their boltgun with chirurgeon’s tools
-One Celestian may be upgraded to a Dialogus, replacing their boltgun with a laud hailer
-The Dialogus may take items from the Ecclesiarchy Relics list
-One Celestian may take one of the following:
- Blessed standard 
- Sacred Banner of the Order Militant (one per army)

-One other Celestian may take a Simulacrum Imperialis

-Any other Celestian may take items from the Melee Weapons, Ranged Weapons, Special Weapons and/or Heavy Weapons lists.

The word other makes this incredibly clear hospitalier/diolgus/banner and sigmentum models may not take from the lists.
