### ISSUE TITLE
[Anon] Bug report: Chaos Space Marines - Codex.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-7th-edition#2972] opened 2016-12-06 12:31 UTC
**File:** Chaos Space Marines - Codex.catz

**BattleScribe version:** 2.00.09

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** I'm trying to make a Thousand sons army list but the exhalted sorcerers are not in the HQ choice.  I am making it a supplement thousand sons detachment but he still isn't there. Am I not putting something in that I should be or am I using the wrong book.

**Comment by FarseerVeraenthis** [comment] 2016-12-06 15:24
In a CAD or a formation?

**Comment by DrSentryy** [comment] 2016-12-06 19:23
In a CAD I selected the supplement but they aren't there but everything else seemed fine and showed up

**Comment by FarseerVeraenthis** [comment] 2016-12-06 19:36
This is a duplicate of #2952

**Closed as completed by FarseerVeraenthis** 2016-12-06 19:36 UTC
Labels: duplicate
