### ISSUE TITLE
CSM Black Crusade Detachment - Veterans of the Long War pts.

### ISSUE THREAD

**Issue by Dyemor** [BSData/wh40k-7th-edition#2471] opened 2016-09-15 11:14 UTC
Veterans of the Long War should be free when taken on any of the formations within the Black Crusade detachment but instead it costs points.

**Comment by GenWilhelm** [comment] 2016-09-15 11:19
Duplicate of #2460

**Closed as completed by GenWilhelm** 2016-09-15 11:19 UTC
Labels: duplicate

**Comment by Dyemor** [comment] 2016-09-15 13:21
Sorry about that, I thought I had searched all the open bugs. Will try not to do it again.
