### ISSUE TITLE
[Anon] Bug report: Dark_Eldar_Codex_(2014).catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-7th-edition#1858] opened 2016-02-11 19:32 UTC
**File:** Dark_Eldar_Codex_(2014).catz

**BattleScribe version:** ~~1.05.17~~ 1.15.07

**Platform:** Windows

**Dropbox:** No

**Description:** The "Dark Eldar Raven Fighter" from forgeworld is missing. Cannot be found in CAD. (not to be confused with "Razorwing Jetfighter" or "Voidraven Bomber").

Rules are in Aeronautica book.

Confirmed missing on Android and Windows.

_edit: ~amis92_

**Comment by Norion12** [comment] 2016-02-11 19:35
Listed this as version 1.05.07, should be 1.15.07  I am using the most recent version of Battlescribe

**Comment by amis92** [comment] 2016-02-11 21:18
Oh wait. It's duplicate of #1816

**Closed as completed by amis92** 2016-02-11 21:18 UTC
Labels: duplicate
