### ISSUE TITLE
[Anon] Bug report: Grey Knights - Codex (2014).catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-7th-edition#2738] opened 2016-11-10 14:40 UTC
**File:** Grey Knights - Codex (2014).catz

**BattleScribe version:** 2.00.05

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** Hi there! Trying to create a Nemesis Strike Force detachment of Grey Knights. There are no HQs, Troops, Fast Attack, etc. available. Only option is Uncategorized. Under that heading I can select option: Nemesis Strike Force, which has no options itself.

Thanks and keep up the good work!

**Comment by GenWilhelm** [comment] 2016-11-16 10:49
This was fixed in 182133637d8c8dc056044637f1ef85cdd47958f7.

**Closed as completed by GenWilhelm** 2016-11-16 10:49 UTC
Labels: duplicate, deprecated

**Comment by amis92** [comment] 2016-11-17 15:17
Duplicate of #2772
