### ISSUE TITLE
[Anon] Bug report: Space Marines - Codex (2015).catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-7th-edition#1209] opened 2015-07-01 16:01 UTC
**File:** Space Marines - Codex (2015).catz

**BattleScribe version:** 1.15.06

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** Crashes on piepad when adding any space marine unit choice.

**Comment by amis92** [comment] 2015-07-01 20:16
Duplicate of #1152

**Closed as completed by amis92** 2015-07-01 20:16 UTC
Labels: duplicate
