### ISSUE TITLE
Bug report Eldar Craftworlds - Codex (2015).catz: Wraithblades

### ISSUE THREAD

**Issue by Owlsbane** [BSData/wh40k-7th-edition#2067] opened 2016-04-03 22:44 UTC
File: Eldar Craftworlds - Codex (2015).catz

BattleScribe version: 1.15.07

Platform: Windows

Dropbox: No

Description: Two issues, possibly interrelated -
1] In the Roster Selection Pane, the information shown is incorrect. It shows the gear and the models at the same depth in the tree, instead of the 5 Wraithblades first and then the Ghostswords as a branch to them
2] In roster statistics overview they show as having one model too many

**Comment by efalsken** [comment] 2016-04-04 00:17
Can not reproduce. Possibly a duplicate of #2068

**Closed as completed by efalsken** 2016-04-04 00:17 UTC
Labels: bug

**Comment by Owlsbane** [comment] 2016-04-04 00:33
Can I do this when it's already closed, or should I open a new one?

Regarding 2] above, when I open up a new roster (CAD) and choose a unit of Wraithblades, then look at the statistics it shows the unit as consisting of 6 models instead of 5. But when I change their loadout from Ghostswords to Ghost Axe and Forcefield the stats change to 5.

**Comment by efalsken** [comment] 2016-04-04 00:48
oh, i see. Let me try to fix that. No need to do it in a separate ticket.
