### ISSUE TITLE
[Anon] Bug report: Chaos Daemons (40K) - Codex.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-7th-edition#2169] opened 2016-05-13 20:44 UTC
**File:** Chaos Daemons (40K) - Codex.catz

**BattleScribe version:** 1.15.07

**Platform:** Windows

**Dropbox:** No

**Description:** When selecting any formation (or the Daemonic Incursion detachments) from the new Curse of the Wulfen update for Chaos Daemons, I am not able to select Deathdealer as an artefact of Khorne for my Herald of Khorne. I can select Deathdealer when I am looking at Bloodthirsters, but not the Herald. According to the rulebook, it is usable by both.

**Comment by cartag** [comment] 2016-05-13 20:54
I'm 90% positive it should be just for daemon princes and bloodthirsters, but I'll double check when I get home.

**Comment by threllen** [comment] 2016-05-13 21:42
Hmmm... maybe this pdf I have is just too blurry then. It looks like a "1" next to the name (which would be DP/Herald) but maybe it is a 2... if so, my bad!

**Comment by azraelcow** [comment] 2016-05-13 21:57
Yeah it's definitely a superscript 2, even with the original I need to squint to read it.

**Comment by threllen** [comment] 2016-05-13 21:58
Thank you! Silly GW printing.Guess I got it stuck in my head the first time I saw it that it was a 1 and didn't look closely enough to realize it was actually a 2...

**Comment by cartag** [comment] 2016-05-13 23:04
Working as intended, closing.

**Closed as completed by cartag** 2016-05-13 23:04 UTC
Labels: invalid
