### ISSUE TITLE
[Anon] Bug report: Chaos Space Marines - Codex.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-7th-edition#2963] opened 2016-12-05 21:20 UTC
**File:** Chaos Space Marines - Codex.catz

**BattleScribe version:** 2.00.12

**Platform:** iPhone / iPod / iPad

**Dropbox:** Yes

**Description:** I can't add a thousands sons war coven detachment as part of my CSM force when I attempt to add it takes me back to the force selection screen

**Comment by cartag** [comment] 2016-12-05 23:17
Duplicate of #2954

**Closed as completed by cartag** 2016-12-05 23:17 UTC
Labels: duplicate
