### ISSUE TITLE
[Anon] Bug report: Space Wolves - Codex.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-7th-edition#1646] opened 2015-12-04 17:07 UTC
**File:** Space Wolves - Codex.catz

**BattleScribe version:** 1.15.07

**Platform:** Windows

**Dropbox:** No

**Description:** Relic Leviatan Siege dreadnought is not listed for space wolves

http://www.forgeworld.co.uk/resources/PDF/Datasheets/LeviathanSiegeDreadnoughtRules.pdf

**Comment by amis92** [comment] 2015-12-12 06:54
Actually duplicate of #1514

**Closed as completed by amis92** 2015-12-12 06:54 UTC
Labels: duplicate
