### ISSUE TITLE
Eldar Craftworlds (2015)

### ISSUE THREAD

**Issue by 0-Apparition-0** [BSData/wh40k-7th-edition#1224] opened 2015-07-05 02:13 UTC
Cant seem to find the Warzone:Valedor formations for craftworld or apocalypse ?

**Comment by zurran** [comment] 2016-01-09 03:25
I cant either

**Comment by efalsken** [comment] 2016-01-09 07:24
This is known. They will be in the big Craftworlds update I'm working on.

**Comment by amis92** [comment] 2016-01-29 19:39
Duplicate of #1613

**Closed as completed by amis92** 2016-01-29 19:39 UTC
Labels: duplicate, enhancement
