### ISSUE TITLE
[Anon] Bug report: Chaos Space Marines - Codex.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-7th-edition#2674] opened 2016-11-05 14:15 UTC
**File:** Chaos Space Marines - Codex.catz

**BattleScribe version:** 2.00.06

**Platform:** Android

**Dropbox:** Yes

**Description:** Even after enabling the option for Forgeworld models they do not appear as options in the Chaos Space Marine army lists. No hidden options either, which means no Fire Raptor, Blught Drones or Belakor. 
This was not an issue until a few days after Battle Scribe updated their app.

**Comment by cartag** [comment] 2016-11-05 15:10
Update your data files. In CSM v2 this is no longer an issue. Duplicate of #2644

**Closed as completed by cartag** 2016-11-05 15:10 UTC
Labels: duplicate
