### ISSUE TITLE
[Anon] Bug report: Space Wolves - Codex.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-7th-edition#2129] opened 2016-04-29 17:58 UTC
**File:** Space Wolves - Codex.catz

**BattleScribe version:** 1.15.07

**Platform:** Android

**Dropbox:** No

**Description:** SW file is missing the relic Leviathan. Confirmed as per PDF it is selectable for SW and company of the great wolf

**Comment by SuperPranx** [comment] 2016-04-29 21:36
Duplicate of #2120

**Closed as completed by SuperPranx** 2016-04-29 21:36 UTC
Labels: duplicate
