### ISSUE TITLE
[Anon] Bug report: Space Marines - Codex (2015).catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-7th-edition#1199] opened 2015-06-30 17:18 UTC
**File:** Space Marines - Codex (2015).catz

**BattleScribe version:** 1.15.06

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** Can create a new roster, but once the roster is created the list selection screen locks up when I try to add any units to it.

**Comment by amis92** [comment] 2015-06-30 17:27
Duplicate of #1152

**Closed as completed by amis92** 2015-06-30 17:27 UTC
Labels: duplicate
