### ISSUE TITLE
[Anon] Bug report: Skitarii - Codex.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-7th-edition#2045] opened 2016-03-30 21:24 UTC
**File:** Skitarii - Codex.catz

**BattleScribe version:** 1.15.07

**Platform:** Android

**Dropbox:** Yes

**Description:** In the formation dominus maniple, the dominus techpriest doesn't have the refractor shield, instead there is list with none, which is not option in the codex, and the conversion field has a cost of 10 and it should be 5.

Thank you.

**Comment by OftKilted** [comment] 2016-03-31 01:21
Appears to be a duplicate of #2009

**Comment by hisop** [comment] 2016-03-31 11:24
Will be resolved in #2009

**Closed as completed by hisop** 2016-03-31 11:24 UTC
Labels: duplicate
