### ISSUE TITLE
Tau breacher team

### ISSUE THREAD

**Issue by Jery77** [BSData/wh40k-7th-edition#1581] opened 2015-11-08 19:33 UTC
Guardian Drone cost = 0, need to be 12

**Comment by efalsken** [comment] 2015-11-09 02:55
Please confirm where in the list you see this? I do not see it in the current version of the files. I think this is a duplicate of a previous bug already fixed. I see 12 points per MV36 Guardian Drone (in Striker and Breacher teams).

**Closed as completed** 2015-11-13 07:20 UTC
Labels: deprecated
