### ISSUE TITLE
[Anon] Bug report: Chaos Space Marines - Codex.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-7th-edition#3509] opened 2017-03-08 00:12 UTC
**File:** Chaos Space Marines - Codex.catz

**BattleScribe version:** 2.00.14

**Platform:** Windows

**Dropbox:** Yes

**Description:** when selecting an artefact weapon for the chaos Lord it says: Chaos Lord has 1 too mny selections from Chaos Artefact Weapons (maximum 0) while in codex (page 93) it says "may take items from.... or Chaos Artefacts section of the wargear list.

**Comment by FarseerVeraenthis** [comment] 2017-03-08 05:51
Duplicate of #3499

**Closed as completed by FarseerVeraenthis** 2017-03-08 05:51 UTC
Labels: duplicate
