### ISSUE TITLE
Eldar Craftworlds - Craftworld Warhost not showing Core/Aux/Command Choices

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-7th-edition#2626] opened 2016-11-03 06:36 UTC
**File:** Eldar Craftworlds - Codex (2015).catz

**BattleScribe version:** 2.00.04

**Platform:** Android

**Dropbox:** No

**Description:** The Craftworld Warhost is not allowing me to select any formations for core, command, or Auxiliary. The options just aren't showing up. Also, can supplement Iyanden please be added? It is legal as of the draft FaQ.

**Comment by amis92** [comment] 2016-11-08 16:53
Duplicate of #2685

**Closed as completed by amis92** 2016-11-08 16:53 UTC
Labels: duplicate
