### ISSUE TITLE
[Anon] Bug report: Space Marines - Codex (2015).catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-7th-edition#1207] opened 2015-07-01 07:26 UTC
**File:** Space Marines - Codex (2015).catz

**BattleScribe version:** 1.15.06

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** When I attempt to create a new roster using the Gladius strike force detachment, the app becomes unresponsive. I can't add formations or use any menu options and the roster does not save.

**Comment by amis92** [comment] 2015-07-01 20:12
Duplicate of #1152

**Closed as completed by amis92** 2015-07-01 20:12 UTC
Labels: duplicate
