### ISSUE TITLE
[Anon] Bug report: Space Wolves - Codex.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-7th-edition#3276] opened 2017-01-20 15:38 UTC
**File:** Space Wolves - Codex.catz

**BattleScribe version:** 2.00.10

**Platform:** Windows

**Dropbox:** No

**Description:** Thunderwolf Cavalry leader does not have an option to get rid of their ranged weapons.

**Comment by GenWilhelm** [comment] 2017-01-20 15:39
Duplicate of #3261.

**Closed as completed by GenWilhelm** 2017-01-20 15:39 UTC
Labels: duplicate
