### ISSUE TITLE
[Anon] Bug report: Astra Militarum - Codex.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-7th-edition#1647] opened 2015-12-05 07:00 UTC
**File:** Astra Militarum - Codex.catz

**BattleScribe version:** 1.14.07

**Platform:** Android

**Dropbox:** No

**Description:** The new Cadian Battle Group formation doesn't work because there's nothing listed when it's opened. All that's there is the name of the formation and a requirement for another command choice, which isn't there to be selected.

**Comment by kombatrok** [comment] 2015-12-05 11:34
Also the formations should be available as stand alone formations outside of the battlegroup

**Comment by amis92** [comment] 2015-12-08 06:34
Duplicate of #1642.

**Closed as completed by amis92** 2015-12-08 06:34 UTC
Labels: duplicate
