### ISSUE TITLE
[Anon] Bug report: Space Marines - Codex (2015).catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-7th-edition#3365] opened 2017-02-05 19:41 UTC
**File:** Space Marines - Codex (2015).catz

**BattleScribe version:** 2.00.11

**Platform:** Windows

**Dropbox:** No

**Description:** Space Marine CAD's cannot have any additional formations added.

**Comment by FarseerVeraenthis** [comment] 2017-02-05 20:31
duplicate of #3332 
we're working on it...

**Closed as completed by FarseerVeraenthis** 2017-02-05 20:31 UTC
Labels: duplicate
