### ISSUE TITLE
[Anon] Bug report: Chaos Space Marines - Codex.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-7th-edition#733] opened 2015-02-13 10:04 UTC
**File:** Chaos Space Marines - Codex.catz

**BattleScribe version:** 1.15.06

**Platform:** Android

**Dropbox:** Yes

**Description:** Chaos space Marine squads bigger then ten models get flagged as not allowed. Cultists squads have problem adding heavy weapons.

**Comment by NebSeele** [comment] 2015-02-13 11:16
I have identified the root cause of both. Cultists heavy weapons seem to only account for autopistols for the minimum variable so I should have that fixed soon enough. I'll increase the CSM count back up to 19 (as the champ is required in the unit regardless) as well.

Edit: CSM bug was exclusive to the Boltgun option. I accidentally set the decrementing of possible max selections to itself instead of the CCW option triggering it. I have tested the fix and it works as intended for all three options.

 As for the cultist bug, I am working out a solution to this problem as this is a side effect bug (and a complex one at that, I really wish there was a mixed option up to arbitary number modifier)

**Comment by NebSeele** [comment] 2015-02-13 13:12
I have fixed the CSM issue and uploaded it to the github. At present I am unsure how to fix the cultists problem. 
The old layout caused problems with selecting any weapon (causing serious problems with the roster) and selecting all or none obviously killed mix and match units (to which the Cultist unit is hardly the only one to suffer this problem).
The current issue is that the modifiers for the heavy weapons are based on each increment of either a full auto-pistol of auto-gun load-out per heavy weapon (so 9 of either for 1 heavy weap, 19 for 2 and 29 for three, some variation based on if heavy weapons exist). 

The combinations that cause this bug do not have a fix inside battlescribe. The modifiers are arbitrary figures. To do each individual combination for each variation would cause problems on the mobile devices, maybe the desktop machines as well. To leave it as is obviously won't fix that particular issue. 

I'll look into seeing if I can implement the old Cultist model count system to account  for the heavy weapon, with the Autogun/Autopistol modifiers altering the min/max for those particular models (similar to current csm). I'll leave the Battlescribe bug tag on, as fixed numbers as absolute really aren't that friendly for a good roster.

**Closed as completed** 2015-02-13 13:30 UTC
Labels: bug, BattleScribe bug
