### ISSUE TITLE
[Anon] Bug report: Chaos - Khorne Daemonkin.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-7th-edition#1042] opened 2015-06-02 06:01 UTC
**File:** Chaos - Khorne Daemonkin.catz

**BattleScribe version:** 1.15.07

**Platform:** Windows

**Dropbox:** No

**Description:** I have updated the Codex: Khorne Daemonkin to have "Angron, Daemon Primarch of the World Eaters" as a Lord of War, i have corrected the file already but there seems to be an issue with the upload, therefore i am posting a bug with hopes of communication so i can get the new file uploaded and available for everyone else!

PS: I retrieved the profile for Angron out of an issue of White Dwarf
Thank you,
Randy Rodgers
(rmrodgers2011@gmail.com)

**Comment by NebSeele** [comment] 2015-06-02 09:32
might I ask which white dwarf this is just so I can confirm this myself? If there's genuine Angron rules for Daemonkin (that's 7th Ed rules at that) then I'd be more than glad to update the ruleset.

**Comment by senpai514** [comment] 2015-06-02 10:05
as the user is anon you should email him he wont know about your reply otherwise unless he decides to actually log on and check

**Comment by senpai514** [comment] 2015-06-02 10:09
@NebSeele just did a quick search online and all I found in regards to Angron was dated 2008 so if that's what he's referring to than its a no go.

**Comment by amis92** [comment] 2015-06-02 22:05
Is there no profile for him in Horus Heresy books?

**Comment by senpai514** [comment] 2015-06-02 22:08
For the regular primarch yes there is, not for the evolved daemon primarch
I think they make make those later as the series progresses.

**Comment by amis92** [comment] 2015-06-24 20:39
Ok, I guess as he said "retrieved profile" he means he created the rules on basis of those Daemon Primarchs there are, but used old existing profile. Closing, because that's outdated and nonsense currently. We'll wait for Horus Heresy.

**Closed as completed by amis92** 2015-06-24 20:39 UTC
Labels: enhancement, question, not resolved
