### ISSUE TITLE
[Anon] Bug report: Space Marines - Codex (2015).catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-7th-edition#1133] opened 2015-06-25 07:26 UTC
**File:** Space Marines - Codex (2015).catz

**BattleScribe version:** 1.15.06

**Platform:** iPhone / iPod / iPad

**Dropbox:** Yes

**Description:** V4 still crashes app. However if I select Astra Militarum as the primary force then select SM as another Combined Arms detachment the following Error Message appears: "Error Loading Catalogue: Object Reference not set to an instance of an object."    Good luck.

**Comment by amis92** [comment] 2015-06-25 22:46
Duplicate of #1138

**Closed as completed** 2015-06-27 14:03 UTC
Labels: duplicate, BattleScribe bug
