### ISSUE TITLE
[Anon] Bug report: Necrons - Codex (2015).catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-7th-edition#1482] opened 2015-10-02 20:13 UTC
**File:** Necrons - Codex (2015).catz

**BattleScribe version:** 1.15.07

**Platform:** Android

**Dropbox:** Yes

**Description:** in the formation detachment options you are missing the formation for Star God (tesseract vault, ctan deceiver, ctan nightbringer, transcendent ctan),Flayed Ones, and Deathmarks. please add these options. remove option for immortals for the Pyrrhian Eternals - no longer available. night scythe, death scythe, night shroud, remove option for fighter ace - no longer available.

**Comment by cartag** [comment] 2015-10-02 20:59
Duplicate of #1480

**Closed as completed by cartag** 2015-10-02 20:59 UTC
Labels: duplicate
