### ISSUE TITLE
[Anon] Bug report: Space Wolves - Codex.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-7th-edition#1886] opened 2016-02-17 20:09 UTC
**File:** Space Wolves - Codex.catz

**BattleScribe version:** 1.15.07

**Platform:** Windows

**Dropbox:** Yes

**Description:** For the space wolf Wolf Claw Strike force there are no Auxillary choices for the Muderpack. There are no core choices for the other Companies (firehowlers, deathwolves, ironwolves)

**Comment by OftKilted** [comment] 2016-02-17 21:18
Appears to be a duplicate of https://github.com/BSData/wh40k/issues/1881

**Closed as completed** 2016-02-19 00:23 UTC
Labels: duplicate
