### ISSUE TITLE
[Anon] Bug report: Chaos Space Marines - Codex.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-7th-edition#3641] opened 2017-04-08 10:02 UTC
**File:** Chaos Space Marines - Codex.catz

**BattleScribe version:** 2.00.32

**Platform:** Android

**Dropbox:** No

**Description:** Chaos Lord of Death Guard with mark of Nurgle do not have option to take Blight grenades

**Comment by FarseerVeraenthis** [comment] 2017-04-10 20:23
Duplicate of #3634

**Closed as completed by FarseerVeraenthis** 2017-04-10 20:23 UTC
Labels: duplicate
