### ISSUE TITLE
Dark Eldar - Haemonculus Covens - Formation Issue

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-7th-edition#3456] opened 2017-02-23 01:10 UTC
**File:** Dark Eldar - Supplement - Haemonculus Covens.catz

**BattleScribe version:** 2.00.25

**Platform:** Android

**Dropbox:** No

**Description:** Issue persists,  formation detatchment requires 1 formation, only option is carnival of pain, its not posible to select an individual formation without having to select carnval of pain wich gives the error that all other formations are required.

Options should be: 
         Formation:Scalple squadron

Present issue
          Formation: Carnival of Pain
            Formation: Scalple squadron

Formations should be accessed separately

**Comment by FarseerVeraenthis** [comment] 2017-02-23 08:24
Duplicate of #3452 and #3453 
This will be available in the next release. Please do not raise another bug report.

**Closed as completed by FarseerVeraenthis** 2017-02-23 08:24 UTC
Labels: duplicate, deprecated
