### ISSUE TITLE
Please Control Cypher, he's upsetting the Dark Angels...

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-7th-edition#3621] opened 2017-04-04 11:47 UTC
**File:** Warhammer40K.gstz

**BattleScribe version:** 2.00.32

**Platform:** Android

**Dropbox:** Yes

**Description:** Cypher (selectionEntry id="1595-cd9a-be0f-b396") and The Fallen can be widely used with entries of the Dark angels faction, which is not correct since Gathering Storm 3:
"Neither Cypher nor the Fallen may be included in an army that includes any models with the Dark Angels Faction"
Should this not mean that they cannot be used in any roster together whether bound, or unbound? I understand this is complex as it is across multiple catalogues, however thought that as a shared entry there might be a way to have some contraints based off force catalogue used. Haven't been able to look at this myself, but thought it should be flagged.

**Comment by FarseerVeraenthis** [comment] 2017-04-04 12:45
Duplicate of #3615
This is not possible to implement at present.

**Comment by Thairne** [comment] 2017-04-04 12:55
I think while rambling I just came unto the solution...

**Comment by Thairne** [comment] 2017-04-04 13:03
I can't be upset by non-existing persons!
Neither bird persons, phoenix persons or cypher persons!
ALSO I'M NOT UPSET DAMNIT!

Also, I did not commit a fix that did not fix that you cannot select something that does not exist.

**Closed as completed** 2017-04-04 13:04 UTC
Labels: duplicate

**Comment by FarseerVeraenthis** [comment] 2017-04-04 14:32
That clears that up then, ~~NOTHING HAPPENED ON CALIBAN, so there's NO-ONE CALLED CYPHER, who's totally NOT hidden in the Dark Angels list...~~
IF THERE WAS A PERSON BY THE NAME OF CYPHER CARRYING WHAT MAY OR MAY NOT BE A HISTORICAL BLADE OF SIGNIFICANT IMPORTANCE HE HAS NOW BEEN SEQUESTERED IN THE ROCK AND ~~HIDDEN~~ IS BEING INTERROGATED BY THE CHAPLAINS.
