### ISSUE TITLE
[Anon] Bug report: Chaos Space Marines - Codex.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-7th-edition#3036] opened 2016-12-11 19:23 UTC
**File:** Chaos Space Marines - Codex.catz

**BattleScribe version:** 2.00.13

**Platform:** Android

**Dropbox:** No

**Description:** The thousands sons grand coven is missing some formations in then command section. 

and the thousand son's units are missing from then unbound detatchmemt.

**Comment by cartag** [comment] 2016-12-12 03:23
Duplicate of #3022, already resolved just not had a release yet.

**Closed as completed by cartag** 2016-12-12 03:23 UTC
Labels: duplicate
