### ISSUE TITLE
[Anon] Bug report: Blood Angels - Codex (2014).catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-7th-edition#2549] opened 2016-10-27 17:49 UTC
**File:** Blood Angels - Codex (2014).catz

**BattleScribe version:** 1.15.07

**Platform:** Windows

**Dropbox:** No

**Description:** Assault Squad should be 85pts with jump-packs standard and dedicated transports free if the jp's are removed - this data file (as with HoR and standard 40k files) does not allow for this...

Points need to be rechecked and options need to be recalculated...

**Comment by GenWilhelm** [comment] 2016-10-27 18:00
Duplicate of #2529

**Closed as completed by GenWilhelm** 2016-10-27 18:00 UTC
Labels: duplicate
