### ISSUE TITLE
[Anon] Bug report: Dark Eldar - Supplement - Haemonculus Covens.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-7th-edition#3453] opened 2017-02-22 20:25 UTC
**File:** Dark Eldar - Supplement - Haemonculus Covens.catz

**BattleScribe version:** 2.00.25

**Platform:** Android

**Dropbox:** No

**Description:** Selections in formation detatchment only has carnival of pain, selection in uncategorized says formations and shows list,  error message reads formations must have minimum selection one, only has carnival of pain wich requires all formations, cant acces formations to run on theyr own

**Comment by GenWilhelm** [comment] 2017-02-22 23:51
Duplicate of #3452.

**Closed as completed by GenWilhelm** 2017-02-22 23:51 UTC
Labels: duplicate, deprecated
