### ISSUE TITLE
[Anon] Bug report: Space Marines - Raven Guard Talon Strike Force.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-7th-edition#1589] opened 2015-11-13 05:36 UTC
**File:** Space Marines - Raven Guard Talon Strike Force.catz

**BattleScribe version:** 1.15.07

**Platform:** Android

**Dropbox:** No

**Description:** In the Ravenhawk formation, when an Ironclad or venerable Dreadnought is selected it reads as not having a Dreadnought selected.

**Comment by amis92** [comment] 2015-11-13 07:18
Duplicate of #1539 (in comments).

**Closed as completed by amis92** 2015-11-13 07:18 UTC
Labels: duplicate
