### ISSUE TITLE
Eldar Craftworlds - Craftworld Warhost not showing Core/Aux/Command Choices

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-7th-edition#2685] opened 2016-11-07 06:49 UTC
**File:** Eldar Craftworlds - Codex (2015).catz

**BattleScribe version:** 2.00.06

**Platform:** Android

**Dropbox:** No

**Description:** At Eldar craftworld warhost after "Select Force org" there are no selection for "core", "auxillary", etc

**Comment by FarseerVeraenthis** [comment] 2016-11-07 21:15
I'll have a go at this...

**Comment by efalsken** [comment] 2016-11-07 22:57
chances are that it's just missing a few constraints. "hide if ancestor is not instance of ...." but the "Core" and "aux" force org types may not have been copied over correctly. Ping me if you need me to look at it.

**Comment by FarseerVeraenthis** [comment] 2016-11-08 08:50
There are two "Core", "Aux", and "Command" options in the drop down, I switched the Craftworld Battlehost Formations from one to the other and the problem is "fixed" as of last night, however, I didn't manage to fix the constraints to correctly reflect the RAW in the Codex.
@efalsken do you want me to comit my changes as they are so you can take a look at the constraints??

**Comment by FarseerVeraenthis** [comment] 2016-11-08 09:15
This is a duplicate issue: see #2626 and #2630

**Comment by efalsken** [comment] 2016-11-08 16:45
Push your change to your own branch and create a Pull Request. I'll pull it in and merge my fixes.

**Comment by amis92** [comment] 2016-11-08 16:51
@FarseerVeraenthis please label as duplicate only additional issues, the first one (or the best one, if it has better description) , should be labeled as bug. Right now there are three marked as duplicates. Also those which are duplicates should be closed immediately after labeling as duplicate and commenting with a number of the original/actual issue.

**Closed as completed** 2016-11-08 21:55 UTC
Labels: bug
