### ISSUE TITLE
[Anon] Bug report: Orks - Codex.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-7th-edition#2159] opened 2016-05-11 16:16 UTC
**File:** Orks - Codex.catz

**BattleScribe version:** 1.15.07

**Platform:** Android

**Dropbox:** No

**Description:** The ork codex file displays the following errors when I access my  rosters

> Ork: Codex (2015) v57: The catalogue data file is invalid: 
> model.catalogue.Modifier@1610f4a2:
> Modifier must have a field that exists
> model.catalogue.Modifier@3f08c44c:
> Modifier must have a field that exists 

Message began to appear this morning after refreshing data files at apps behest.

**Comment by HeWhoWatches** [comment] 2016-05-15 21:09
Fixed in latest release: https://github.com/BSData/wh40k/releases/tag/v4.14.1

**Closed as completed by HeWhoWatches** 2016-05-15 21:09 UTC
Labels: duplicate

**Comment by amis92** [comment] 2016-05-15 22:42
Duplicate of https://github.com/BSData/wh40k/issues/2158
