### ISSUE TITLE
[Anon] Bug report: Chaos Space Marines - Codex.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-7th-edition#2644] opened 2016-11-04 00:59 UTC
**File:** Chaos Space Marines - Codex.catz

**BattleScribe version:** 2.00.06

**Platform:** Android

**Dropbox:** No

**Description:** If i choose the option "Show Forgeworld" nothing happens. Forgeworld units are not shown in the roster. Tried to reinstall data files and updated it but this doesnt help.

**Comment by cartag** [comment] 2016-11-04 01:04
Duplicate of #2612

**Closed as completed by cartag** 2016-11-04 01:04 UTC
Labels: duplicate
