### ISSUE TITLE
[Anon] Bug report: Chaos Space Marines - Codex.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-7th-edition#2484] opened 2016-09-21 13:15 UTC
**File:** Chaos Space Marines - Codex.catz

**BattleScribe version:** 1.15.08

**Platform:** Android

**Dropbox:** No

**Description:** The Chaos Dark Apostle has no option to take the Scrolls of Magnus, even after it was confirmed in FAQ that this is possible and makes the Apostle a ML1 Psyker. I have checked and the Chaos Lord has the option to but Apostle does not.

**Comment by GenWilhelm** [comment] 2016-09-21 13:29
Duplicate of #2487

**Closed as completed by GenWilhelm** 2016-09-21 13:29 UTC
Labels: duplicate
