### ISSUE TITLE
[Anon] Bug report: Blood Angels - Codex (2014).catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-7th-edition#2497] opened 2016-09-26 19:06 UTC
**File:** Blood Angels - Codex (2014).catz

**BattleScribe version:** 1.15.10

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** There should be a terminator assault squad option under the Archangels Demi-company, instead of a tactical squad option. Hope this helps thank you.

**Comment by GenWilhelm** [comment] 2016-09-26 20:43
Duplicate of #2493

**Closed as completed by GenWilhelm** 2016-09-26 20:43 UTC
Labels: duplicate
