### ISSUE TITLE
[Anon] Bug report: Tau - Codex (2015).catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-7th-edition#2562] opened 2016-10-30 07:47 UTC
**File:** Tau - Codex (2015).catz

**BattleScribe version:** 2.00.01

**Platform:** Android

**Dropbox:** No

**Description:** XV25 Stealth battlesuite
Bug: roaster error message  showing 3 Shas'ui are needed if the team is composted by 2 Shas'ui and 1 Shas'vre.
Fix: no error message if the team models are three either  all Shas'ui, or 2 Shas'ui and 1 Sha'vre

**Comment by efalsken** [comment] 2016-10-31 16:42
duplicate of #2554

**Closed as completed** 2016-10-31 16:42 UTC
Labels: duplicate
