### ISSUE TITLE
[Anon] Bug report: Space Wolves - Codex.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-7th-edition#1997] opened 2016-03-11 17:01 UTC
**File:** Space Wolves - Codex.catz

**BattleScribe version:** 1.15.07

**Platform:** Android

**Dropbox:** Yes

**Description:** The rune priest is able to take a thunderwolf mount

**Comment by SuperPranx** [comment] 2016-03-11 17:21
Whoever starts working on this will need to check all places/detachments/formations that mention a rune priest because at the moment I can't reproduce this.

**Comment by Gnofry** [comment] 2016-03-13 20:26
I think this is more of "I think the rune priest should be able to take a thunderwolf mount", which is wrong. None of the entries I looked at had any mention of a thunderwolf mount (Rune Priest, Grimnar's War Council, Heralds of the Great Wolf, and Wyrdstorm). Entries being the catalog entries.

**Comment by SuperPranx** [comment] 2016-03-13 20:42
I think you might be right. I also didn't find any instance of a rune priest that could do that in the data file. I'm going to go ahead and close the issue.

**Closed as completed by SuperPranx** 2016-03-13 20:42 UTC
Labels: vague report
