### ISSUE TITLE
[Anon] Bug report: Tau - Codex (2015).catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-7th-edition#2524] opened 2016-10-12 11:16 UTC
**File:** Tau - Codex (2015).catz

**BattleScribe version:** 1.15.07

**Platform:** Windows

**Dropbox:** No

**Description:** https://drive.google.com/file/d/0B__WUzGeu6hKUkJmemtuam5KYTA/view?usp=sharing

**Comment by GenWilhelm** [comment] 2016-10-12 14:34
Duplicate of #2522

**Closed as completed by GenWilhelm** 2016-10-12 14:34 UTC
Labels: duplicate

**Comment by amis92** [comment] 2016-10-19 22:14
Just for reference, the pic from the link: 
![image](https://cloud.githubusercontent.com/assets/2671396/19539537/2e3bbb34-965a-11e6-9d05-3f829c303a4c.png)

**Comment by efalsken** [comment] 2016-10-20 04:48
I specifically checked for this issue when I updated the files with the new Heavy Rail Cannon. Please update your data files.
