### ISSUE TITLE
[Anon] Bug report: Eldar Craftworlds - Codex (2015).catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-7th-edition#1248] opened 2015-07-10 02:06 UTC
**File:** Eldar Craftworlds - Codex (2015).catz

**BattleScribe version:** 1.15.04

**Platform:** Windows

**Dropbox:** No

**Description:** It does not allow me to have a farseer skyrunner and a generic farseer in the same list, even if they are separate detatchments. It says all farseers must have the same amount of skyrunner. This is not supported by the codex as best I could see.

**Comment by Itsacon** [comment] 2015-07-29 09:02
Duplicate of #1239

**Closed as completed** 2015-07-29 09:19 UTC
Labels: bug, duplicate
