### ISSUE TITLE
[Anon] Bug report: Space Wolves - Codex (2015).catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-7th-edition#2847] opened 2016-11-22 19:20 UTC
**File:** ~~Tau - Codex (2015).catz~~ Space Wolves - Codex.catz

**BattleScribe version:** 2.00.07

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** Harald death wolf has to pay for a storm shield but his wargear page says he already has won

**Comment by amis92** [comment] 2016-11-23 09:47
I *believe* Harald Deathwolf sounds like Space Wolves hero, so I changed the report and title.

**Comment by SuperPranx** [comment] 2016-11-23 10:36
Harald Deathwolf has a Storm Shield and doesn't need to pay for one. The only things he can buy are up to 2 Fenrisian Wolves at 8pts/wolf. The issue submitter is wrong.

**Comment by GenWilhelm** [comment] 2016-11-23 10:41
@SuperPranx Anon is saying that BattleScribe gives the option to purchase, whereas the codex says he has one by default.

**Comment by SuperPranx** [comment] 2016-11-23 10:43
Yeah, my bad. I just read #2848 which is a duplicate of this one and it's explained better there :)

**Closed as completed** 2016-11-23 11:24 UTC
Labels: duplicate
