### ISSUE TITLE
[Anon] Bug report: Orks - Codex.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-7th-edition#2172] opened 2016-05-15 18:24 UTC
**File:** Orks - Codex.catz

**BattleScribe version:** 1.15.07

**Platform:** Android

**Dropbox:** No

**Description:** Since the last download of the files, always is saying that the directory has files that @44 ... Modifiers a file exist... And similars and crash when i intend to add a new force in the rost.

**Comment by HeWhoWatches** [comment] 2016-05-15 18:28
Should be fixed when the next release occurs - see also #2158 #2159 #2165

**Comment by HeWhoWatches** [comment] 2016-05-15 21:10
Fixed in latest release: https://github.com/BSData/wh40k/releases/tag/v4.14.1

**Closed as completed by HeWhoWatches** 2016-05-15 21:10 UTC
Labels: duplicate

**Comment by amis92** [comment] 2016-05-15 22:42
Duplicate of https://github.com/BSData/wh40k/issues/2158
