### ISSUE TITLE
[Anon] Bug report: Space Marines - Raven Guard Talon Strike Force.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-7th-edition#1594] opened 2015-11-14 05:37 UTC
**File:** Space Marines - Raven Guard Talon Strike Force.catz

**BattleScribe version:** 1.15.07

**Platform:** Android

**Dropbox:** No

**Description:** The Ravenhawk Assault Formation doesn't register as having a Dreadnought selected if an Ironclad or Venerable dead nought is chosen.

**Comment by amis92** [comment] 2015-11-14 07:42
Duplicate of #1539 (in comments).

**Closed as completed by amis92** 2015-11-14 07:42 UTC
Labels: duplicate
