### ISSUE TITLE
[Anon] Bug report: Chaos Space Marines - Codex.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-7th-edition#1958] opened 2016-03-04 09:38 UTC
**File:** Chaos Space Marines - Codex.catz

**BattleScribe version:** 1.15.07

**Platform:** Android

**Dropbox:** Yes

**Description:** Juggernaut for ChaosLord (with mark of Khorne) is not available!

**Comment by cartag** [comment] 2016-03-04 15:58
Duplicate of #1918. Will be pushed with next release.

**Closed as completed by cartag** 2016-03-04 15:58 UTC
Labels: duplicate
