### ISSUE TITLE
[Anon] Bug report: Chaos Space Marines - Codex.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-7th-edition#1363] opened 2015-08-15 05:09 UTC
**File:** Chaos Space Marines - Codex.catz

**BattleScribe version:** 1.15.07

**Platform:** Windows

**Dropbox:** No

**Description:** Lucis the eternal changes Noise Marines to Troop choices but an error comes saying that you have too many selections of noise marines if you pick any.

**Comment by cartag** [comment] 2015-08-18 00:11
Kharn and the Berzerkers (that's a good name for a George Thorogood and the Destroyers cover band) isn't working either, same bug.

**Comment by pruneface** [comment] 2015-08-20 00:20
Are you creating the list as unbound? I did that and got the same issue as your describing

**Comment by NebSeele** [comment] 2015-08-20 04:52
<i>Note: Does anyone else have issues using the Force type modifier? because this issue is stemming from that. I cannot tell if it's because I am not using it correctly or if the thing's bugged, but in every occasion I have gone to use it in the CSM AND Daemons codices (both having force related conditions), the thing spits an error in regards to selections and the Force org chart.</i>

The bug appears in Combined Arms as well. The issue stems from the aforementioned Force type modifier not rolling the max selections around to account for the force. The only real fix I can think of is to use maxSelections, but then that applies for the WHOLE roster, not that single force.

**Comment by cartag** [comment] 2015-08-20 04:58
It works for Tzeentch and Nurgle troop choices though, I checked.

**Comment by cartag** [comment] 2015-08-20 05:02
Spotted the problem. Nurgle is set to set it to 0 if it has 0 selections of Typhus or MoN. Zerkers have it set to 0 if it has less than 1 selection. It's a subtle difference, but it may account for it.  

Zerkers: < 1
Slaanesh: < 1
Nurgle: 0
Tzeentch: 0

**Comment by NebSeele** [comment] 2015-08-20 05:38
It's weird that's the cause as many of my other modifiers work for the "less than" variable, but in any case if that's the cause then I'll fix it along with the other bug fixes.

**Comment by NebSeele** [comment] 2015-08-20 08:18
nope, seems to be the MaxInForce that's the issue, as it's now equal to 0 MoK or 0 Berzerkers.

**Comment by NebSeele** [comment] 2015-08-26 13:48
Had to move Kharn to a shared entry to fix the problem, but it's fixed now. Edit: The condition bracket also had to be "AND"

**Closed as completed** 2015-08-26 13:48 UTC
Labels: bug, BattleScribe bug
