### ISSUE TITLE
[Anon] Bug report: Space Marines - Codex (2015).catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-7th-edition#1820] opened 2016-02-02 11:30 UTC
**File:** Space Marines - Codex (2015).catz

**BattleScribe version:** 1.15.07

**Platform:** Android

**Dropbox:** No

**Description:** You mistakenly removed the option for Venerable Dreadnoughts to take Drop Pods as Dedicated Transports.

**Comment by penguin20000** [comment] 2016-02-02 11:39
Duplicate of #1799 

A change was made so that if you take more than 1 Dreadnought you cannot take any Transport as per the codex.
"If the unit includes no additional Venerable Dreadnoughts, it may select a Drop Pod as a Dedicated Transport."

**Comment by penguin20000** [comment] 2016-02-11 12:36
This isn't an issue on iPhone either, closing.

**Closed as completed by penguin20000** 2016-02-11 12:36 UTC
Labels: duplicate, unable to reproduce
