### ISSUE TITLE
[Anon] Bug report: Space Wolves - Codex.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-7th-edition#3121] opened 2016-12-21 02:09 UTC
**File:** Space Wolves - Codex.catz

**BattleScribe version:** 2.00.16

**Platform:** Android

**Dropbox:** No

**Description:** Space Wolf Wolf Guard Terminators just got a recent loadout update and no longer have the option to take a heavy flamer.

**Comment by alphalas** [comment] 2016-12-21 02:52
Duplicate of #3116

**Closed as completed by alphalas** 2016-12-21 02:52 UTC
Labels: duplicate
