### ISSUE TITLE
iOS - Dark Angels autosave fail

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-7th-edition#1254] opened 2015-07-12 03:46 UTC
**File:** Dark Angels - Codex (2015).catz

**BattleScribe version:** 1.15.07

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** I build my list as per usual, however as soon as I leave it it all gets lost. Nothing seems to save bar the basic Demi company. All upgrades, auxiliary and any other force I add are lost.
Thank you for doing what you do!

**Comment by Thairne** [comment] 2015-07-12 11:28
Hm. Seems to be iOS specific and therefore most likely a BS Bug. Maybe caused by the fix to the crashing issue on iOS?

**Comment by amis92** [comment] 2015-07-12 16:30
Similar to #1228 and #1229. :<

**Comment by amis92** [comment] 2015-07-26 18:57
Seems like it was fixed in some recent update.

**Closed as completed by amis92** 2015-07-26 18:57 UTC
Labels: BattleScribe bug
