### ISSUE TITLE
CSM Black Crusade detachment

### ISSUE THREAD

**Issue by wm95414125** [BSData/wh40k-7th-edition#2460] opened 2016-09-10 22:23 UTC
All units still have points values for the Veterans of the Long War upgrade - but Traitors Hate rules state that VotLW is free for all units taken within the detachment

**Comment by cartag** [comment] 2016-09-10 22:55
This may take a bit for me to easily get implemented. It's something that is already done in BS2 prep work, but the checks used simply don't exist in the current version of BS.

**Comment by balannear** [comment] 2016-09-23 16:02
The problem is still there, veteran of the long war pts. can it be fix? thank you.

**Comment by cartag** [comment] 2016-09-23 16:21
It simply isn't possible as it stands now with BS 1.X without an absolutely massive amount of work.

**Comment by amis92** [comment] 2016-11-03 19:52
@cartag I guess it's done now for 2.0?

**Comment by cartag** [comment] 2016-11-03 19:54
Yes and no. It's fixed in the sense that the BC detachment gives VotLW for free, but the things I used also made it free in any other detachment too due to a bug in BS.

**Comment by skonk** [comment] 2016-11-14 10:02
I'm still seeing points costs for VoTLW on Raptors and Warptalons.

Also; unrelated to this but I'll mentioned it here.

The Cult of Destruction formation is enforcing 1 Warpsmith per formation; when the formation actually allows for 1 to 3.

**Closed as completed** 2016-11-16 21:51 UTC
Labels: BattleScribe bug, not resolved
