### ISSUE TITLE
[Anon] Bug report: Orks - Codex.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-7th-edition#1374] opened 2015-08-21 01:07 UTC
**File:** Orks - Codex.catz

**BattleScribe version:** 1.15.07

**Platform:** Windows

**Dropbox:** No

**Description:** In the Ork Codex, the options for Warbosses and Big Meks include "Gifts of Gork and Mork", but the battlescribe data file implemented these wargear options incorrectly. The problem is that the data file only allows you to select 1! of the "Gifts of Gork and Mork" per HQ, but this isn't how the codex works. You are allowed to take every single "Gift of Gork and Mork" on one HQ, BUT you cannot take more than 1 of the SAME GIFT in your army.

**Comment by afraeve** [comment] 2015-08-21 04:50
Duplicate of #1046 - The wargear list section in the middle of the book states: "A model can take one of the following".

**Closed as completed by afraeve** 2015-08-21 04:50 UTC
Labels: duplicate, invalid
