### ISSUE TITLE
[Anon] Bug report: Space Wolves - Codex.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-7th-edition#3273] opened 2017-01-20 02:10 UTC
**File:** Space Wolves - Codex.catz

**BattleScribe version:** 2.00.23

**Platform:** Android

**Dropbox:** Yes

**Description:** Thunderwolf Cavalry Pack Leader is still showing weapon load out error with minimum/maximum selection. Also showing ranged weapon as a requirement when it is not. 
Air superiority detachment - no longer listing "air superiority" special rule.

**Comment by FarseerVeraenthis** [comment] 2017-01-20 06:19
Duplicate of #3261

**Closed as completed by FarseerVeraenthis** 2017-01-20 06:19 UTC
Labels: bug, duplicate
