### ISSUE TITLE
[Anon] Bug report: Chaos Space Marines - Codex.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-7th-edition#1925] opened 2016-02-27 11:14 UTC
**File:** Chaos Space Marines - Codex.catz

**BattleScribe version:** 1.15.07

**Platform:** Android

**Dropbox:** No

**Description:** There is no way to Select  a juggernaut of khorne (and maybe the other Steeds  of the respective chaos gods, but havent tried them) as a mount for a chaos lord. Have activated hidden units, reinstalled battlescribe as well as the Data Files,  triple Checked everything.. please fix!

**Comment by OftKilted** [comment] 2016-02-27 12:04
Steeds require selecting a mark of chaos.
"A model may only take a demonic steed if it has the mark of the appropriate chaos God" (p. 67 'Daemonic Steeds' Chaos Space Marine Codex)

**Comment by cartag** [comment] 2016-02-27 16:03
Duplicate of #1918

**Closed as completed by cartag** 2016-02-27 16:03 UTC
Labels: duplicate
