### ISSUE TITLE
[Anon] Bug report: Orks - Codex.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-7th-edition#1947] opened 2016-03-02 23:20 UTC
**File:** Orks - Codex.catz

**BattleScribe version:** 1.15.07

**Platform:** Windows

**Dropbox:** No

**Description:** When using the Great Waaagh-band Detachment, apparently with the revised supplement anyone that can use Gifts of Gork and Mork can also use Orkimedes' Kustom Gubbinz.  Unfortunately, it seems I can only outfit my Warboss with the Gubbinz, when (from what I've read) I should be able to give him Da Lucky Stikk from Codex: orks.

I may be wrong on this because I've only seen it from the screenshot and don't actually own the revised Ghazgkhull supplement.
Thanks.

**Comment by afraeve** [comment] 2016-03-02 23:51
Duplicate of #1937 
You're not wrong. I uploaded a fix for this yesterday, so you'll be able to see it after we make the next public release.

**Closed as completed by afraeve** 2016-03-02 23:51 UTC
Labels: duplicate
