### ISSUE TITLE
[Anon] Bug report: Orks - FW - Dread Mob.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-7th-edition#1801] opened 2016-01-22 20:05 UTC
**File:** Orks - FW - Dread Mob.catz

**BattleScribe version:** 1.15.07

**Platform:** Android

**Dropbox:** No

**Description:** The ork dredd mob file has the wrong point values. Deff dredd are 75, should be 80, killer kanz are 35 should be 50. Burna boyz are 15 should be 16.  Looks like the old 5th ed codex point values not the 7th edition point values.

**Comment by afraeve** [comment] 2016-01-23 12:57
Duplicate of #1755

**Closed as completed by afraeve** 2016-01-23 12:57 UTC
Labels: duplicate
