### ISSUE TITLE
[Anon] Bug report: Necrons - Codex (2015).catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-7th-edition#1875] opened 2016-02-15 16:38 UTC
**File:** Necrons - Codex (2015).catz

**BattleScribe version:** 1.15.09

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** Overlord in the decurion detachment should be interchangeable with some anmeld characters and command barge. The specific are: catacomb command barge, nemesor zahndrekh, trazyn the infinite and anrakyr the traveller.

**Comment by OftKilted** [comment] 2016-02-17 13:46
In "Nec Decurion Detachment" using catalog Necrons: Codex (2015) v11 (current publicly available) I'm unable to replicate the issue.
All of the choices indicated are available to choose as your overlord choice.

**Comment by penguin20000** [comment] 2016-02-17 19:35
Just checked on iPhone with the latest data files & these options are all available.

**Comment by OftKilted** [comment] 2016-02-17 20:07
1 Overlord is required, this overlord can be one of the items listed. To change the 'option' one selects the 'overlord' and then chooses one of the alternates.
Invalid, unable to reproduce with the current catalog.
Closing https://github.com/BSData/wh40k/issues/1875

**Closed as completed by OftKilted** 2016-02-17 20:07 UTC
Labels: invalid, unable to reproduce
