### ISSUE TITLE
[Anon] Bug report: Space Wolves - Codex.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-7th-edition#1877] opened 2016-02-16 01:53 UTC
**File:** Warhammer40K.gstz

**BattleScribe version:** 1.15.06

**Platform:** Windows

**Dropbox:** No

**Description:** The stats for the wulfen do not appear in the 'View Roster' option

It shows the unit just not the S/T/I etc

Same issue on android. Looking at the HTML now so will let you know if I figure it out

**Comment by Raek0ne** [comment] 2016-02-16 01:55
![wulfen](https://cloud.githubusercontent.com/assets/17262819/13065046/758ed512-d426-11e5-8977-44b0f5a5acbc.png)

**Comment by penguin20000** [comment] 2016-02-16 12:12
Dupe of #1873

**Closed as completed by penguin20000** 2016-02-16 12:12 UTC
Labels: duplicate
