### ISSUE TITLE
[Anon] Bug report: Tyranids - Codex.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-7th-edition#1339] opened 2015-08-04 12:41 UTC
**File:** Tyranids - Codex.catz

**BattleScribe version:** 1.15.07

**Platform:** Android

**Dropbox:** No

**Description:** In the hq slot the tyranid prime should not be called a trygon prime nor should its stats match those of the aforementioned monstrous creature. The selection rules are correct but the stats given in the stat block are incorrect and should natch the codex tyranids instead.

**Comment by Itsacon** [comment] 2015-08-04 14:17
Duplicate of #1226, please make sure you are using the latest version of the datafiles.

**Closed as completed** 2015-08-15 06:38 UTC
Labels: duplicate
