### ISSUE TITLE
[Anon] Bug report: Eldar Craftworlds - Codex (2015).catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-7th-edition#1802] opened 2016-01-22 23:59 UTC
**File:** Eldar Craftworlds - Codex (2015).catz

**BattleScribe version:** 1.15.07

**Platform:** Android

**Dropbox:** No

**Description:** I am wanting to build a list using the new Pale Courts formations from IA11: Doom of Mymeara - Second Edition. Is anyone working on adding the new options (including shadow spectres, wraithseer etc) to the Eldar Craftworld Warhost files? I'd really like to start playing around with lists for these guys if possible. Thanks!!!

**Comment by efalsken** [comment] 2016-01-23 01:09
Yes. New Craftworlds-with-IA11 data file is on its way by the end of the month.

**Comment by amis92** [comment] 2016-01-23 17:04
Isn't this duplicate of #1727 ?

**Comment by efalsken** [comment] 2016-01-25 08:12
Yup. duplicate. Closing.

**Closed as completed by efalsken** 2016-01-25 08:12 UTC
Labels: duplicate, enhancement
