### ISSUE TITLE
[Anon] Tau - Farsight Enclaves - Damocles: Mont'ka

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-7th-edition#1623] opened 2015-11-30 14:54 UTC
**File:** Tau - Supplement - Farsight Enclaves.catz

**BattleScribe version:** 1.17.11

**Platform:** Android

**Dropbox:** No

**Description:** The farsight enclave is not updated to the new tau codex or the damocles crusade mont ka book.

**Comment by Morphyum** [comment] 2015-12-07 11:26
Any news? Would be nice to have this addition :)

**Comment by efalsken** [comment] 2015-12-07 16:46
Fighting some Battlescribe bugs. I'll have some more time to work on it later tonight.

**Comment by Jery77** [comment] 2015-12-07 18:56
I didn't understand.  Can Riptide take signature systems?

**Comment by killroy225** [comment] 2015-12-07 19:49
@Jery77 in the newest book it looks like they cannot take signature systems.

**Comment by efalsken** [comment] 2015-12-07 20:31
Confirmed. Riptide can no longer take Sig Systems as of Mont'ka.

**Comment by Morphyum** [comment] 2015-12-07 23:33
Yea RAW they can't take it, even so that's kinda stupid considering the earth casts array is in there.

**Comment by thezanji** [comment] 2015-12-08 20:32
is there a way to have like an estimation date of when will it be ready? just to calm down my anxiety

thanks a lot.

**Comment by efalsken** [comment] 2015-12-08 20:51
Soon. Probably in the next day or two.

**Comment by lostgrail** [comment] 2015-12-10 17:47
To use the new Mont'ka formations with a "loyalist" Tau Empire army, one would just have to pull the units from the FSE catalogue in a Formation Detachment? Or will they eventually be added to the "Codex" list as well?

**Comment by amis92** [comment] 2015-12-10 18:12
@lostgrail There will be no separate Farsight catalogue. Everything, including stuff from Mont'ka, will be in Codex Tau catalogue. To opt into Farsight Enclaves, one will have to add `Farsight Enclaves` from `No Category`.

**Comment by lostgrail** [comment] 2015-12-10 18:53
That makes sense, since all the units are pulled from the same catalog anyway. Anything I can do to help speed the process along?

**Comment by efalsken** [comment] 2015-12-10 18:58
Not much. There's an open pull request that has all of Mont'ka implemented, but there's one remaining bug with The Eight and their wargear. We might still release it anyway since it's a battlescribe bug.

**Closed as completed** 2015-12-10 20:35 UTC
Labels: enhancement
