### ISSUE TITLE
[Anon] Bug report: Blood Angels - Codex (2014).catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-7th-edition#2494] opened 2016-09-26 13:38 UTC
**File:** Blood Angels - Codex (2014).catz

**BattleScribe version:** 1.15.10

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** Archangels Demi-Company formation has tactical marines listed instead of assault terminators under the veterans entry. It is using the values and options for the tactical marines.

**Comment by GenWilhelm** [comment] 2016-09-26 14:12
Duplicate of #2493

**Closed as completed by GenWilhelm** 2016-09-26 14:12 UTC
Labels: duplicate
