### ISSUE TITLE
Chaos Space Marines - Error When Chaos Lord Takes Artifacts

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-7th-edition#3499] opened 2017-03-06 06:16 UTC
**File:** Chaos Space Marines - Codex.catz

**BattleScribe version:** 2.00.27

**Platform:** Android

**Dropbox:** No

**Description:** There is an error with the chaos Lord taking too many artifact weapons. It gives me the error message "chaos Lord has too many artifact weapons maximum0. He was able.to take one in previous updates. He only has 1 relic as per the new FAQ

**Comment by cartag** [comment] 2017-03-24 00:25
Duplicate of #3474

**Closed as completed by cartag** 2017-03-24 00:25 UTC
Labels: bug
