### ISSUE TITLE
[Anon] Bug report: Blood Angels - Codex (2014).catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-7th-edition#2543] opened 2016-10-24 13:45 UTC
**File:** Blood Angels - Codex (2014).catz

**BattleScribe version:** 1.15.07

**Platform:** Windows

**Dropbox:** No

**Description:** Hi,
Not sure if the devs are the same for the HoR, but there are errors in the codex point costs for units and options.
Assault marines are 85pts and come with jump-packs - dedicated transports are free if the jump-packs are removed. Your data files do not allow for this...could someone please correct it :)

**Comment by GenWilhelm** [comment] 2016-10-24 14:36
Duplicate of #2529

**Closed as completed by GenWilhelm** 2016-10-24 14:36 UTC
Labels: duplicate
