### ISSUE TITLE
[Anon] Bug report: Warhammer40K.gstz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-7th-edition#1284] opened 2015-07-21 15:56 UTC
**File:** Warhammer40K.gstz

**BattleScribe version:** 1.15.07

**Platform:** Android

**Dropbox:** No

**Description:** Codex tyranids:
Tervigon is no longer a separate troop choice, but comes as a "sub equipment" of termagant units.
That means lists will allways lack a troop choice, if you want to field it alongside its 30 compulsory gants, since the tervigon is not counted as one different unit, but part of the termagants infantry.

**Comment by amis92** [comment] 2015-07-22 21:22
Duplicate of #1285

**Closed as completed by amis92** 2015-07-22 21:22 UTC
Labels: duplicate
