### ISSUE TITLE
[Anon] Bug report: Orks - Codex.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-7th-edition#2165] opened 2016-05-13 04:57 UTC
**File:** Orks - Codex.catz

**BattleScribe version:** 1.15.07

**Platform:** Android

**Dropbox:** No

**Description:** Still seeing the error for Orks: Codex (2014) v57, "Modifier must have a field to exist."

Modifier@1a2742f6
Modifier@3299d500

**Comment by HeWhoWatches** [comment] 2016-05-13 05:37
Assuming you have not manually downloaded the fixed cat file from github and replaced the catz file in the data folder then that's correct, yes. The fixed version should be included in the next w40k release (changes are made to the data files all the time, but are only pushed to the appspot site and converted into catz files when a release is created).

**Comment by HeWhoWatches** [comment] 2016-05-13 05:38
See also #2158 #2159

**Comment by HeWhoWatches** [comment] 2016-05-15 21:09
Fixed in latest release: https://github.com/BSData/wh40k/releases/tag/v4.14.1

**Closed as completed by HeWhoWatches** 2016-05-15 21:09 UTC
Labels: duplicate

**Comment by amis92** [comment] 2016-05-15 22:42
Duplicate of https://github.com/BSData/wh40k/issues/2158
