### ISSUE TITLE
[Anon] Bug report: Space Marines - Codex (2015).catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-7th-edition#2831] opened 2016-11-20 21:20 UTC
**File:** Space Marines - Codex (2015).catz

**BattleScribe version:** 2.00.12

**Platform:** Android

**Dropbox:** Yes

**Description:** Venerable drednaught twin linked lascannon costs 15 points in codex, costs 20 points in app.

**Comment by francoisbeaulieu** [comment] 2016-11-21 03:14
Duplicate of #2802

**Closed as completed** 2016-11-21 03:20 UTC
Labels: duplicate
