### ISSUE TITLE
[Anon] Bug report: Sisters of Silence Dataslate.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-7th-edition#3671] opened 2017-04-15 14:55 UTC
**File:** Sisters of Silence Dataslate.catz

**BattleScribe version:** 2.00.19

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** The wicthseekers do not pay an additional 2 points for the flamers. The points are included in the higher unit cost

**Comment by cartag** [comment] 2017-04-15 16:11
Duplicate of #3667

**Closed as completed by cartag** 2017-04-15 16:11 UTC
Labels: duplicate
