### ISSUE TITLE
[Anon] Bug report: Space Marines - Codex (2015).catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-7th-edition#1874] opened 2016-02-15 12:14 UTC
**File:** Space Marines - Codex (2015).catz

**BattleScribe version:** 1.15.07

**Platform:** Android

**Dropbox:** No

**Description:** Venerable Dreadnoughts should have access to Drop Pods.

**Comment by penguin20000** [comment] 2016-02-15 13:32
Duplicate of #1820 & #1799

If you take more than one Venerable Dread i hide the option to take a transport as the codex states you can only take a drop pod if there's only 1 dreadnaught.

Would it be better to just add a validation rule? (I think i also added one anyway to catch invalid builds that have already been made)

**Closed as completed** 2016-02-15 20:24 UTC
Labels: duplicate
