### ISSUE TITLE
Eldar Craftworlds - Craftworld Warhost not showing Core/Aux/Command Choices

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-7th-edition#2630] opened 2016-11-03 11:47 UTC
**File:** Eldar Craftworlds - Codex (2015).catz

**BattleScribe version:** 2.00.05

**Platform:** Android

**Dropbox:** No

**Description:** Eldar Craftword Warhost has no funtionality. Shows no Core, Aux, Command, or Support options. Screenshot avaiable upon request.

**Comment by amis92** [comment] 2016-11-08 16:54
Duplicate of #2685

**Closed as completed by amis92** 2016-11-08 16:54 UTC
Labels: duplicate
