### ISSUE TITLE
[Anon] Bug report: Chaos Space Marines - Codex.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-7th-edition#2015] opened 2016-03-18 12:09 UTC
**File:** Chaos Space Marines - Codex.catz

**BattleScribe version:** 1.15.07

**Platform:** Windows

**Dropbox:** No

**Description:** The price of lightning claws for chaos terminators are wildly inaccurate. According to the codex, a single lightning claw cost 3 pts/model and a pair of lightning claws cost 7 pts/model. In battlescribe, the price for one claw is 5 pts and there is no option for a pair, you can only select a second claw, which costs 17 (!!) pts.That's 15 points too much for a pair of claws.

**Comment by OftKilted** [comment] 2016-03-18 17:18
Chaos Space Marines Codex: There is a 3 point option on the Melee arm, and a 4 point option on the ranged arm for lightning claws.

What version of the file are you using? And can you please provide images of the bug as I'm unable to reproduce the issue with C:SM v193

**Comment by cartag** [comment] 2016-03-21 05:12
What version of the data file are you looking at? I'm not able to duplicate this at all.

**Comment by cartag** [comment] 2016-03-22 00:49
The pricing you list is accurate for Terminators, but the pricings of 5 pts and 17pts is accurate for Chaos Lords or Sorcerors, per page 91 of the codex. They don't get their weapons at the same price of Terminators as a unit. I'm closing this.

**Closed as completed by cartag** 2016-03-22 00:49 UTC
Labels: unable to reproduce
