### ISSUE TITLE
[Anon] Bug report: Space Marines - Codex (2015).catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-7th-edition#1223] opened 2015-07-04 20:39 UTC
**File:** Space Marines - Codex (2015).catz

**BattleScribe version:** 1.15.06

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** I downloaded the update that includes the new space marine codex but it freezes and won't let me build an army list. I input the points value, name my list then press plus sign, I then choose space marine codex 2015 after loading data I press on one of the options (HQ, Troop ect) then it freezes and I have to close down the app to do anything.
I tryed redownloading battlescribe but same problem happens and it's only with the new space marine codex. I hope this helps.

**Comment by amis92** [comment] 2015-07-04 21:36
Duplicate of #1152

**Closed as completed by amis92** 2015-07-04 21:36 UTC
Labels: duplicate
