### ISSUE TITLE
[Anon] Bug report: Eldar Craftworlds - Codex (2015).catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-7th-edition#1328] opened 2015-08-01 16:53 UTC
**File:** Eldar Craftworlds - Codex (2015).catz

**BattleScribe version:** 1.15.07

**Platform:** Mac

**Dropbox:** No

**Description:** Warlock Conclave minimum points is 70, should be 35.

**Comment by Itsacon** [comment] 2015-08-04 13:59
Duplicate of #1277, this was fixed
Please make sure you're using the latest version of the datafiles.

**Closed as completed** 2015-08-19 12:47 UTC
Labels: duplicate
