### ISSUE TITLE
[Anon] Bug report: Space Wolves - Codex.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k-7th-edition#3348] opened 2017-01-31 14:53 UTC
**File:** Space Wolves - Codex.catz

**BattleScribe version:** 2.00.24

**Platform:** Android

**Dropbox:** No

**Description:** Wolf Guard Terminators missing option for Heavy Flamer

**Comment by GenWilhelm** [comment] 2017-01-31 14:54
Duplicate of #3329.

**Closed as completed by GenWilhelm** 2017-01-31 14:54 UTC
Labels: duplicate

**Comment by IronWulfen88** [comment] 2017-02-08 06:03
Issue is still popping up though. on both the pc and tablet versions. not sure what happened. I saw the option pop back up then when I did my latest data update the option went away
